# Generated by Django 2.2.7 on 2019-11-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='type',
        ),
        migrations.DeleteModel(
            name='HouseType',
        ),
    ]
